### ISSUE TITLE
Issue with precompiled version of GumTree

### ISSUE THREAD

**Issue by ASvyatkovskiy** [JetBrains-Research/python-change-miner#9]
Thanks for open sourcing this great tool!

I am seeing `java.lang.NullPointerException` error when using the precompiled `gumtree` binary in the `parse` mode, namely:
```
$ external/compiled/gumtree-2.1.2/bin/gumtree parse 1.py 
java.lang.NullPointerException
```
the error is not specific to an input source code file, and it happened with all the input files I have tried. 

I suspected this could be caused by the `PATH` to `pythonparser` env variable setting. Setting those variables manually changes the error:
```
$ export GUMTREE_PYPARSER_PATH="/tmp"
$ export GUMTREE_PYTHON_BIN=`which python`
$ external/compiled/gumtree-2.1.2/bin/gumtree parse 1.py
java.lang.RuntimeException: 
```

Note: The stock gumtree-2.1.2 version works fine on my system, although I can't use it with the `python-change-miner` tool due to an apparent JSON schema mismatch between what the gumtree generates and what the tool expects (see error message below (*)). Is it possible for you to document the changes necessary in the Gumtree code?

Here are the details about my system:
**$ uname -a
Linux pythiaGPUVM 4.15.0-1106-azure #118 16.04.1-Ubuntu SMP Tue Jan 19 16:13:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
$ python
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.**

(*) error message with stock gumtree-2.1.2
```
$ python tests/test_change_graphs.py 
[13.06.2021 21:32:18] WARNING: pid16011: Change graph building... 
[13.06.2021 21:32:18] WARNING: pid16011: Flow graphs... OK 8ms 
[13.06.2021 21:32:18] ERROR: Unable to build change graph 
Traceback (most recent call last):
  File "tests/test_change_graphs.py", line 23, in _try_build_change_graph
    return changegraph.build_from_files(p1, p2)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/build.py", line 22, in build_from_files
    gt1, gt2 = gumtree.build_from_file(path1), gumtree.build_from_file(path2)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/gumtree.py", line 31, in build_from_file
    return GumTree(src_path, parsed)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/gumtree.py", line 70, in __init__
    self.cnt = self._read_data(self._data.get('root', {}), start_value=0)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/gumtree.py", line 85, in _read_data
    child_node, val = self._read_data(child, start_value=val)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/gumtree.py", line 85, in _read_data
    child_node, val = self._read_data(child, start_value=val)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/gumtree.py", line 89, in _read_data
    node = GumTreeNode(data=start_node)
  File "/datadisk/alexeys/GumTree/python-change-miner/changegraph/gumtree.py", line 250, in __init__
    self.pos = int(data['pos'])
KeyError: 'pos'
Traceback (most recent call last):
  File "tests/test_change_graphs.py", line 417, in <module>
    test_complex_example10()
  File "tests/test_change_graphs.py", line 392, in test_complex_example10
    assert _get_label_to_node_cnt(cg) == {
  File "tests/test_change_graphs.py", line 31, in _get_label_to_node_cnt
    for node in cg.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
```

**Comment by SmirnovOleg** [comment]
Hey, thank you for opening this issue!

I suppose that the problem is with your `GUMTREE_PYPARSER_PATH`. If you are running the miner from `master`-branch, try to set it up this way:
```
export GUMTREE_PYPARSER_PATH=/path/to/python-change-miner/external/pythonparser_3.py
```

Generally, it is set automatically, but only when you are running `python main.py ...` or `python -m pytest`. I will clarify this in README, thanks!

**Comment by ASvyatkovskiy** [comment]
It works now! Thank you for prompt response
